---
title: "Hearts R"
output: html_notebook
---


```{r}
GibbsSampler <- function(nchain, data, init, prop_sd){
  ## Voir les transparents du super cours
  X <- data$X
  Y <- data$Y
  t <- data$t
  cured <-Y==0
  
    
  alpha <- init[1]
  delta <- init[2]
  beta <- exp(alpha)
  theta <- exp(delta)/(1+exp(delta))
  
  chain <- matrix(NA, nchain + 1, 4)
  chain[1,] <- c(alpha,delta, beta, theta)
  for (i in 1:nchain){
    
    ## Mise a jour de Alpha et Beta
    prop <- rnorm(1, alpha, prop_sd[1])
    
    p <- exp(alpha)/(1+exp(alpha))
    p_prop <- exp(prop)/(1+exp(prop))
    
    top <- sum(log(theta+(1-theta)*(1-p_prop)*t) *cured +
      (1 - cured) * (Y*log(p_prop)+X*log(1-p_prop)))- (prop**2)/(2*(prop_sd[1]**2))
    
    bottom <- sum(log(theta+(1-theta)*(1-p)*t) *cured + 
      (1 - cured) * (Y*log(p)+X*log(1-p)))- (alpha**2)/(2*(prop_sd[1]**2))
    
    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      alpha <- prop
      p <- p_prop
      beta <- exp(alpha)
    }
    
    
    ## Mise a jour de Delta et Gamma 
    prop <- rnorm(1, delta, prop_sd[2])
    
    
    
    theta <- exp(delta)/(1+exp(delta))
    theta_prop <- exp(prop)/(1+exp(prop))
    
    top <- sum(log(theta_prop+(1-theta_prop)*(1-p)*t) *cured +
      (1 - cured) * log(1-theta_prop))- (prop**2)/(2*(prop_sd[2]**2))
    
    bottom <- sum(log(theta+(1-theta)*(1-p)*t) *cured + 
      (1 - cured) * log(1-theta))- (delta**2)/(2*(prop_sd[2]**2))
    
    acc_prob <- exp(top - bottom)
    
    if (runif(1) < acc_prob){
      delta <- prop
      theta <- exp(delta)/(1+exp(delta))
    }
    
    
    
    ## Mettre a jour ma chaine
    chain[i+1,] <- c(alpha, delta, beta, theta)
  }
  
  
  return(chain)
  
}
```


Importation des données
```{r}
N <-12
t <- c(11, 11, 17, 22, 9, 6, 5, 14, 9, 7, 22, 51)
x <- c(6, 9, 17, 22, 7, 5, 5, 14, 9, 7, 9, 51)
y <-c(5, 2, 0, 0, 2, 1, 0, 0, 0, 0, 13, 0)
data <- data.frame(x, y, t)
```

Utilisation de l'échantillonneur :
```{r}
sample <- GibbsSampler(10**4, data, c(1, 1), c(10**4, 10**4))

burning <- 1:500
alpha <- sample[1]
summary(sample)
```



